"""Add payment_token_store for OAuth2 providers

Revision ID: 159804ec79c4
Revises: 004invites
Create Date: 2026-01-09 12:03:52.173411

This migration is IDEMPOTENT - skips columns that already exist.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '159804ec79c4'
down_revision = '004invites'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Skip if columns already exist (created by 001cleanslate)
    if column_exists('communities', 'slug'):
        return  # Columns already exist, skip this migration
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('member_cost', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('member_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('communities_name_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_communities_category'))
        batch_op.drop_index(batch_op.f('idx_communities_status'))
        batch_op.drop_index(batch_op.f('ix_invite_code'))
        batch_op.drop_constraint(batch_op.f('uq_invite_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_communities_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_communities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_communities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_visibility'), ['visibility'], unique=False)
        batch_op.drop_column('subscription_fee')
        batch_op.drop_column('image_url')
        batch_op.drop_column('backdrop_image_url')
        batch_op.drop_column('enable_payments')
        batch_op.drop_column('join_fee')
        batch_op.drop_column('subscription_interval')
        batch_op.drop_column('category')
        batch_op.drop_column('auto_approve')
        batch_op.drop_column('is_closed')

    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('community_members_user_id_community_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_community_members_payment'))
        batch_op.drop_index(batch_op.f('idx_community_members_status'))
        batch_op.create_index(batch_op.f('ix_community_members_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_members_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_community_user', ['community_id', 'user_id'])
        batch_op.drop_column('last_payment_date')
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('community_wallets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('community_wallets_account_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('community_wallets_bell_mfb_client_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('community_wallets_community_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_community_wallets_account_number'))
        batch_op.create_index(batch_op.f('ix_community_wallets_account_number'), ['account_number'], unique=True)
        batch_op.drop_index(batch_op.f('ix_community_wallets_bell_mfb_client_id'))
        batch_op.create_index(batch_op.f('ix_community_wallets_bell_mfb_client_id'), ['bell_mfb_client_id'], unique=True)
        batch_op.drop_index(batch_op.f('ix_community_wallets_community_id'))
        batch_op.create_index(batch_op.f('ix_community_wallets_community_id'), ['community_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_community_wallets_status'), ['status'], unique=False)

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interests_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('interests_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_interests_name'))
        batch_op.create_index(batch_op.f('ix_interests_name'), ['name'], unique=True)
        batch_op.drop_index(batch_op.f('ix_interests_slug'))
        batch_op.create_index(batch_op.f('ix_interests_slug'), ['slug'], unique=True)

    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.alter_column('verification_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('verification_number_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('bell_mfb_client_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('bell_mfb_external_reference',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('user_verifications_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_verifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_verifications_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_verifications_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_verifications_verification_number_hash'), ['verification_number_hash'], unique=False)
        batch_op.create_unique_constraint(None, ['bell_mfb_client_id'])
        batch_op.create_unique_constraint(None, ['bell_mfb_external_reference'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('nin',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_id'))
        batch_op.drop_index(batch_op.f('idx_users_phone'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_firebase_uid_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_nin_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.drop_column('password')
        batch_op.drop_column('gender')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('auth_provider')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bill_session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bell_mfb_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bell_mfb_session_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('stamp_duty', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_account_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_bank_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('source_bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('destination_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('destination_account_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('webhook_received_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('reference',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_wallet_transactions_created_at'))
        batch_op.drop_index(batch_op.f('idx_wallet_transactions_reference'))
        batch_op.drop_index(batch_op.f('idx_wallet_transactions_wallet_id'))
        batch_op.drop_constraint(batch_op.f('wallet_transactions_reference_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_wallet_transactions_bell_mfb_reference'), ['bell_mfb_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_bill_session_id'), ['bill_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_payment_intent_id'), ['payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'bill_sessions', ['bill_session_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('narration')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('balance_before')
        batch_op.drop_column('metadata')

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'NGN'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.drop_constraint(batch_op.f('wallets_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_wallets_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_bell_mfb_client_id'), ['bell_mfb_client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_status'))
        batch_op.drop_index(batch_op.f('ix_wallets_bell_mfb_client_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_account_number'))
        batch_op.create_unique_constraint(batch_op.f('wallets_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'NGN'::character varying"))
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('balance_before', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('balance_after', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('narration', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_community_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_bill_session_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_bill_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_bell_mfb_reference'))
        batch_op.create_unique_constraint(batch_op.f('wallet_transactions_reference_key'), ['reference'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_wallet_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('idx_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('webhook_received_at')
        batch_op.drop_column('destination_account_name')
        batch_op.drop_column('destination_account_number')
        batch_op.drop_column('source_bank_name')
        batch_op.drop_column('source_bank_code')
        batch_op.drop_column('source_account_name')
        batch_op.drop_column('source_account_number')
        batch_op.drop_column('description')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('stamp_duty')
        batch_op.drop_column('fee')
        batch_op.drop_column('bell_mfb_session_id')
        batch_op.drop_column('bell_mfb_reference')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('payment_intent_id')
        batch_op.drop_column('bill_session_id')
        batch_op.drop_column('bill_id')
        batch_op.drop_column('community_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_nin_key'), ['nin'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_firebase_uid_key'), ['firebase_uid'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_phone'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('nin',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('firebase_uid',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('user_verifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_verifications_verification_number_hash'))
        batch_op.drop_index(batch_op.f('ix_user_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_verifications_task_id'))
        batch_op.drop_index(batch_op.f('ix_user_verifications_status'))
        batch_op.create_unique_constraint(batch_op.f('user_verifications_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('bell_mfb_external_reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('bell_mfb_client_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('verification_number_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('verification_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interests_slug'))
        batch_op.create_index(batch_op.f('ix_interests_slug'), ['slug'], unique=False)
        batch_op.drop_index(batch_op.f('ix_interests_name'))
        batch_op.create_index(batch_op.f('ix_interests_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('interests_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('interests_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('community_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_wallets_status'))
        batch_op.drop_index(batch_op.f('ix_community_wallets_community_id'))
        batch_op.create_index(batch_op.f('ix_community_wallets_community_id'), ['community_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_community_wallets_bell_mfb_client_id'))
        batch_op.create_index(batch_op.f('ix_community_wallets_bell_mfb_client_id'), ['bell_mfb_client_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_community_wallets_account_number'))
        batch_op.create_index(batch_op.f('ix_community_wallets_account_number'), ['account_number'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('community_wallets_community_id_key'), ['community_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('community_wallets_bell_mfb_client_id_key'), ['bell_mfb_client_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('community_wallets_account_number_key'), ['account_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('community_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=20), server_default=sa.text("'unpaid'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_community_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_community_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_members_status'))
        batch_op.drop_index(batch_op.f('ix_community_members_role'))
        batch_op.drop_index(batch_op.f('ix_community_members_community_id'))
        batch_op.create_index(batch_op.f('idx_community_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_community_members_payment'), ['payment_status', 'next_payment_date'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('community_members_user_id_community_id_key'), ['user_id', 'community_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('auto_approve', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subscription_interval', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('join_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('enable_payments', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('backdrop_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_communities_visibility'))
        batch_op.drop_index(batch_op.f('ix_communities_status'))
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.drop_index(batch_op.f('ix_communities_name'))
        batch_op.drop_index(batch_op.f('ix_communities_invite_code'))
        batch_op.drop_index(batch_op.f('ix_communities_created_by'))
        batch_op.create_unique_constraint(batch_op.f('uq_invite_code'), ['invite_code'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_invite_code'), ['invite_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_communities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_communities_category'), ['category'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('communities_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('member_count')
        batch_op.drop_column('member_cost')
        batch_op.drop_column('visibility')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
