"""Add bio, profile_photo, header_image to users

Revision ID: 62f0fa86bc59
Revises: 159804ec79c4
Create Date: 2026-01-23 13:15:54.279274

This migration is IDEMPOTENT - skips tables/columns that already exist.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '62f0fa86bc59'
down_revision = '159804ec79c4'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # Create payment_token_store table if it doesn't exist
    if not table_exists('payment_token_store'):
        op.create_table('payment_token_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('access_token_expiry', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('refresh_token_expiry', sa.Integer(), nullable=False),
    sa.Column('client_assertion', sa.Text(), nullable=False),
    sa.Column('client_assertion_expiry', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('payment_token_store', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_payment_token_store_provider'), ['provider'], unique=True)

    # Add user columns only if they don't exist
    if not column_exists('users', 'bio'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('profile_photo', sa.String(length=500), nullable=True))
            batch_op.add_column(sa.Column('header_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('header_image')
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('bio')

    with op.batch_alter_table('payment_token_store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_token_store_provider'))

    op.drop_table('payment_token_store')
    # ### end Alembic commands ###
